export const defaultFiltersDataForWathch = [
  {
    id: "category",
    name: "Category",
    type: "checkbox",
    options: [
      { value: "wrist-watches", label: "Wrist Watches" },
      { value: "pocket-watches", label: "Pocket Watches" },
      { value: "smart-watches", label: "Smart Watches" },
      { value: "wall-clocks", label: "Wall Clocks" },
      { value: "desk-clocks", label: "Desk Clocks" },
      { value: "grandfather-clocks", label: "Grandfather Clocks" },
    ],
  },
  {
    id: "brand",
    name: "Brand",
    type: "search-checkbox",
    options: [
      { value: "rolex", label: "Rolex" },
      { value: "omega", label: "Omega" },
      { value: "tag-heuer", label: "Tag Heuer" },
      { value: "patek-philippe", label: "Patek Philippe" },
      { value: "audemars-piguet", label: "Audemars Piguet" },
      { value: "seiko", label: "Seiko" },
      { value: "casio", label: "Casio" },
      { value: "fossil", label: "Fossil" },
      { value: "citizen", label: "Citizen" },
    ],
  },
  {
    id: "price",
    name: "Price Range",
    type: "range",
    min: 0,
    max: 100000,
    step: 100,
    currency: "AED",
    ranges: [
      { value: "0-1000", label: "Under AED 1,000" },
      { value: "1000-5000", label: "AED 1,000 - 5,000" },
      { value: "5000-20000", label: "AED 5,000 - 20,000" },
      { value: "20000-50000", label: "AED 20,000 - 50,000" },
      { value: "50000-100000", label: "AED 50,000 - 100,000" },
    ],
  },
  {
    id: "reference_number", 
    name: "Reference Number",
    type: "search",
    placeholder: "Search reference numbers...",
  },
  {
    id: "movement",
    name: "Movement Type",
    type: "checkbox",
    options: [
      { value: "automatic", label: "Automatic" },
      { value: "quartz", label: "Quartz" },
      { value: "manual-wind", label: "Manual Wind" },
      { value: "solar", label: "Solar" },
      { value: "kinetic", label: "Kinetic" },
    ],
  },
  {
    id: "material",
    name: "Case Material",
    type: "checkbox",
    options: [
      { value: "stainless-steel", label: "Stainless Steel" },
      { value: "gold", label: "Gold" },
      { value: "rose-gold", label: "Rose Gold" },
      { value: "platinum", label: "Platinum" },
      { value: "titanium", label: "Titanium" },
      { value: "ceramic", label: "Ceramic" },
    ],
  },
  {
    id: "strap_material",
    name: "Strap Material",
    type: "checkbox",
    options: [
      { value: "leather", label: "Leather" },
      { value: "metal-bracelet", label: "Metal Bracelet" },
      { value: "rubber", label: "Rubber" },
      { value: "fabric", label: "Fabric" },
      { value: "ceramic", label: "Ceramic" },
    ],
  },
  {
    id: "dial_color",
    name: "Dial Color",
    type: "color-checkbox",
    options: [
      { value: "black", label: "Black", color: "#000000" },
      { value: "white", label: "White", color: "#FFFFFF" },
      { value: "blue", label: "Blue", color: "#2563EB" },
      { value: "green", label: "Green", color: "#059669" },
      { value: "silver", label: "Silver", color: "#9CA3AF" },
      { value: "gold", label: "Gold", color: "#D97706" },
      { value: "mother-of-pearl", label: "Mother of Pearl", color: "#F0F0F0" },
    ],
  },
  {
    id: "water_resistance",
    name: "Water Resistance",
    type: "checkbox",
    options: [
      { value: "30m", label: "30m (Splash Resistant)" },
      { value: "50m", label: "50m (Swimming)" },
      { value: "100m", label: "100m (Snorkeling)" },
      { value: "200m", label: "200m (Recreational Diving)" },
      { value: "300m-plus", label: "300m+ (Professional Diving)" },
    ],
  },
  {
    id: "features",
    name: "Features",
    type: "checkbox",
    options: [
      { value: "chronograph", label: "Chronograph" },
      { value: "date-display", label: "Date Display" },
      { value: "moon-phase", label: "Moon Phase" },
      { value: "gmt", label: "GMT" },
      { value: "tourbillon", label: "Tourbillon" },
      { value: "skeleton", label: "Skeleton Dial" },
      { value: "luminous", label: "Luminous Hands" },
      { value: "alarm", label: "Alarm" },
    ],
  },
  {
    id: "gender",
    name: "Gender",
    type: "checkbox",
    options: [
      { value: "men", label: "Men" },
      { value: "women", label: "Women" },
      { value: "unisex", label: "Unisex" },
    ],
  },
  {
    id: "condition",
    name: "Condition",
    type: "checkbox",
    options: [
      { value: "new", label: "Brand New" },
      { value: "pre-owned", label: "Pre-owned" },
      { value: "vintage", label: "Vintage" },
      { value: "refurbished", label: "Refurbished" },
    ],
  },
  {
    id: "availability",
    name: "Availability",
    type: "checkbox",
    options: [
      { value: "in-stock", label: "In Stock" },
      { value: "pre-order", label: "Pre-order" },
      { value: "limited-edition", label: "Limited Edition" },
    ],
  },
];
